"""colletions and collectionItems tablenames added

Revision ID: 8a301c87de0e
Revises: 
Create Date: 2019-11-20 14:01:56.141079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a301c87de0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_name')
    )
    op.create_table('collection_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=64), nullable=True),
    sa.Column('species', sa.String(length=64), nullable=True),
    sa.Column('width', sa.String(length=64), nullable=True),
    sa.Column('durability', sa.String(length=64), nullable=True),
    sa.Column('length', sa.String(length=64), nullable=True),
    sa.Column('iw_name', sa.String(length=64), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_item')
    op.drop_table('collection')
    # ### end Alembic commands ###
